// Generated by tools/build-apps-script-index.js. Edit files in src/ instead.
(function (window) {
  const App = window.MentoringWorkspace = window.MentoringWorkspace || {};

  App.Config = {
    storageKey: "mentoring-workspace-v4",
    statusLabels: {
      not_started: "Not started",
      in_progress: "In progress",
      waiting: "Waiting",
      blocked: "Blocked",
      done: "Done",
    },
    statusAliases: {
      open: "in_progress",
    },
    defaults: {
      title: "Mentoring Workspace",
      mentor: "Mentor",
      mentee: "Mentee",
      people: ["Mentor", "Mentee"],
      startDate: "2026-06-01",
      docName: "Local daily log",
      sheetName: "Local task table",
    },
  };
})(window);


(function (window) {
  const App = window.MentoringWorkspace = window.MentoringWorkspace || {};

  function createId(prefix) {
    return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
  }

  function todayInput() {
    return toDateInput(new Date());
  }

  function parseDate(value) {
    if (!value) return null;
    const [year, month, day] = String(value).split("-").map(Number);
    if (!year || !month || !day) return null;
    return new Date(year, month - 1, day);
  }

  function stripTime(date) {
    return new Date(date.getFullYear(), date.getMonth(), date.getDate());
  }

  function addDays(date, days) {
    const next = new Date(date);
    next.setDate(next.getDate() + days);
    return next;
  }

  function toDateInput(date) {
    if (!(date instanceof Date) || Number.isNaN(date.getTime())) return "";
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  }

  function isDateInput(value) {
    return /^\d{4}-\d{2}-\d{2}$/.test(String(value || ""));
  }

  function formatShortDate(value) {
    const date = parseDate(value);
    return date ? date.toLocaleDateString([], { month: "short", day: "numeric" }) : "No date";
  }

  function formatLongDate(value) {
    const date = parseDate(value);
    return date ? date.toLocaleDateString([], { month: "long", day: "numeric", year: "numeric" }) : "Unscheduled";
  }

  function formatDateTime(value) {
    if (!value) return "Never";
    return new Date(value).toLocaleString([], {
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
    });
  }

  function escapeHtml(value) {
    return String(value ?? "")
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;")
      .replaceAll('"', "&quot;")
      .replaceAll("'", "&#039;");
  }

  function unique(values) {
    const seen = new Set();
    return values
      .map((value) => String(value || "").trim())
      .filter((value) => {
        if (!value || seen.has(value.toLowerCase())) return false;
        seen.add(value.toLowerCase());
        return true;
      });
  }

  function includesText(value, query) {
    return String(value || "").toLowerCase().includes(String(query || "").trim().toLowerCase());
  }

  App.Utils = {
    addDays,
    createId,
    escapeHtml,
    formatDateTime,
    formatLongDate,
    formatShortDate,
    includesText,
    isDateInput,
    parseDate,
    stripTime,
    todayInput,
    toDateInput,
    unique,
  };
})(window);


(function (window) {
  const App = window.MentoringWorkspace = window.MentoringWorkspace || {};
  const { Config, Utils } = App;

  function normalizeData(data) {
    const fallback = createDefaultData();
    const source = data && typeof data === "object" ? data : {};
    const project = normalizeProject(source.project || fallback.project);
    const tasks = Array.isArray(source.tasks) ? source.tasks.map(normalizeTask).filter((task) => task.title) : fallback.tasks;
    const dailyLogs = Array.isArray(source.dailyLogs) ? source.dailyLogs.map(normalizeLog).filter((log) => log.date) : [];
    const people = Utils.unique([...(project.people || []), ...tasks.map((task) => task.owner)]);

    return {
      version: 4,
      project: {
        ...project,
        people: people.length ? people : Config.defaults.people,
      },
      tasks,
      dailyLogs,
      sync: {
        mode: "local",
        docName: Config.defaults.docName,
        docUrl: "",
        sheetName: Config.defaults.sheetName,
        sheetUrl: "",
        lastSync: "",
        ...(source.sync || {}),
      },
    };
  }

  function normalizeProject(project) {
    const title = sanitizePublicLabel(project.title, Config.defaults.title);
    const mentor = sanitizePublicLabel(project.mentor, Config.defaults.mentor);
    const mentee = sanitizePublicLabel(project.mentee || project.intern, Config.defaults.mentee);
    const people = Array.isArray(project.people) ? project.people : [mentor, mentee];

    return {
      title,
      mentor,
      mentee,
      people: Utils.unique(people.map((person) => sanitizePublicLabel(person, ""))).concat(
        Config.defaults.people.filter((person) => !people.includes(person))
      ),
      startDate: Utils.isDateInput(project.startDate) ? project.startDate : Config.defaults.startDate,
    };
  }

  function sanitizePublicLabel(value, fallback) {
    const text = String(value || "").trim();
    if (!text) return fallback;
    return text;
  }

  function normalizeTask(task) {
    const normalizedStatus = Config.statusAliases[task.status] || task.status;
    const status = Config.statusLabels[normalizedStatus] ? normalizedStatus : "not_started";
    const scheduledDate = task.scheduledDate || task.doDate;
    return {
      id: task.id || Utils.createId("task"),
      title: String(task.title || "").trim(),
      status,
      owner: String(task.owner || task.assignee || Config.defaults.mentee).trim(),
      scheduledDate: Utils.isDateInput(scheduledDate) ? scheduledDate : "",
      deadline: Utils.isDateInput(task.deadline) ? task.deadline : "",
      updatedAt: task.updatedAt || new Date().toISOString(),
    };
  }

  function normalizeLog(log) {
    return {
      id: log.id || Utils.createId("log"),
      date: Utils.isDateInput(log.date) ? log.date : Utils.todayInput(),
      workedOn: String(log.workedOn || "").trim(),
      notes: String(log.notes || "").trim(),
      blockers: String(log.blockers || "").trim(),
      nextStep: String(log.nextStep || "").trim(),
      createdAt: log.createdAt || new Date().toISOString(),
      figureName: String(log.figureName || "").trim(),
      figureDescription: String(log.figureDescription || "").trim(),
    };
  }

  function createDefaultData() {
    const startDate = Config.defaults.startDate;
    return {
      version: 4,
      project: {
        title: Config.defaults.title,
        mentor: Config.defaults.mentor,
        mentee: Config.defaults.mentee,
        people: [...Config.defaults.people],
        startDate,
      },
      tasks: [
        task("Define goals and success criteria", "in_progress", "Mentor", startDate, Utils.toDateInput(Utils.addDays(Utils.parseDate(startDate), 2))),
        task("Set up the shared workspace", "not_started", "Mentee", Utils.toDateInput(Utils.addDays(Utils.parseDate(startDate), 1)), Utils.toDateInput(Utils.addDays(Utils.parseDate(startDate), 4))),
        task("Review background materials", "waiting", "Mentee", Utils.toDateInput(Utils.addDays(Utils.parseDate(startDate), 2)), Utils.toDateInput(Utils.addDays(Utils.parseDate(startDate), 6))),
        task("Confirm the first checkpoint meeting", "done", "Mentor", startDate, startDate),
        task("Prepare midpoint progress summary", "not_started", "Mentee", Utils.toDateInput(Utils.addDays(Utils.parseDate(startDate), 42)), Utils.toDateInput(Utils.addDays(Utils.parseDate(startDate), 48))),
      ],
      dailyLogs: [],
      sync: {
        mode: "local",
        docName: Config.defaults.docName,
        docUrl: "",
        sheetName: Config.defaults.sheetName,
        sheetUrl: "",
        lastSync: "",
      },
    };
  }

  function task(title, status, owner, scheduledDate = "", deadline = "") {
    return normalizeTask({
      id: Utils.createId("task"),
      title,
      status,
      owner,
      scheduledDate,
      deadline,
      updatedAt: new Date().toISOString(),
    });
  }

  function getPeople(data) {
    return Utils.unique([
      ...(data.project?.people || []),
      data.project?.mentor,
      data.project?.mentee,
      ...data.tasks.map((taskItem) => taskItem.owner),
      ...Config.defaults.people,
    ]);
  }

  App.Data = {
    createDefaultData,
    getPeople,
    normalizeData,
    normalizeLog,
    normalizeTask,
  };
})(window);


(function (window) {
  const App = window.MentoringWorkspace = window.MentoringWorkspace || {};
  const { Config, Data } = App;

  function createProvider() {
    const hasAppsScript = typeof google !== "undefined" && google.script && google.script.run;
    if (hasAppsScript) {
      return {
        mode: "google",
        loadState: () => callServer("apiGetState"),
        submitDailyLog: (log) => callServer("apiSubmitDailyLog", log),
        upsertTask: (task) => callServer("apiUpsertTask", task),
        deleteTask: (id) => callServer("apiDeleteTask", id),
      };
    }
    return createLocalProvider();
  }

  function callServer(functionName, ...args) {
    return new Promise((resolve, reject) => {
      google.script.run
        .withSuccessHandler(resolve)
        .withFailureHandler((error) => reject(new Error(error.message || String(error))))
        [functionName](...args);
    });
  }

  function createLocalProvider() {
    return {
      mode: "local",
      async loadState() {
        return getLocalData();
      },
      async submitDailyLog(log) {
        const data = getLocalData();
        data.dailyLogs.push(Data.normalizeLog(log));
        stampLocalSync(data);
        saveLocalData(data);
        return data;
      },
      async upsertTask(task) {
        const data = getLocalData();
        const clean = Data.normalizeTask(task);
        const index = data.tasks.findIndex((item) => item.id === clean.id);
        if (index >= 0) data.tasks[index] = clean;
        else data.tasks.push(clean);
        data.project.people = Data.getPeople(data);
        stampLocalSync(data);
        saveLocalData(data);
        return data;
      },
      async deleteTask(id) {
        const data = getLocalData();
        data.tasks = data.tasks.filter((task) => task.id !== id);
        stampLocalSync(data);
        saveLocalData(data);
        return data;
      },
  };
  }

  function getLocalData() {
    const raw = localStorage.getItem(Config.storageKey);
    if (!raw) return Data.createDefaultData();
    try {
      return Data.normalizeData(JSON.parse(raw));
    } catch {
      return Data.createDefaultData();
    }
  }

  function saveLocalData(data) {
    localStorage.setItem(Config.storageKey, JSON.stringify(Data.normalizeData(data)));
  }

  function stampLocalSync(data) {
    data.sync = {
      ...data.sync,
      mode: "local",
      lastSync: new Date().toISOString(),
    };
  }

  App.Providers = {
    createProvider,
  };
})(window);


(function (window, document) {
  const App = window.MentoringWorkspace = window.MentoringWorkspace || {};
  const { Config, Data, Providers, Utils } = App;
  const MAX_FIGURE_BYTES = 5 * 1024 * 1024;
  const TASK_TONES = ["terra", "sage", "ochre", "clay", "moss", "stone"];

  const state = {
    data: null,
    taskFilter: "all",
    timeline: {
      query: "",
      type: "all",
      person: "all",
      status: "all",
      date: "all",
      view: "list",
    },
    editingTaskId: "",
    provider: null,
    busy: false,
  };

  const els = {};

  function init() {
    cacheElements();
    state.provider = Providers.createProvider();
    bindEvents();
    loadState();
  }

  function cacheElements() {
    Object.assign(els, {
      projectTitle: document.querySelector("#projectTitle"),
      peopleSummary: document.querySelector("#peopleSummary"),
      settingsButton: document.querySelector("#settingsButton"),
      dailyLogForm: document.querySelector("#dailyLogForm"),
      logDate: document.querySelector("#logDate"),
      submitLogButton: document.querySelector("#submitLogButton"),
      clearLogButton: document.querySelector("#clearLogButton"),
      figureInput: document.querySelector("#figureInput"),
      figureDescription: document.querySelector("#figureDescription"),
      newTaskTitle: document.querySelector("#newTaskTitle"),
      newTaskAssignee: document.querySelector("#newTaskAssignee"),
      newTaskStatus: document.querySelector("#newTaskStatus"),
      newTaskScheduledDate: document.querySelector("#newTaskScheduledDate"),
      newTaskDeadline: document.querySelector("#newTaskDeadline"),
      addTaskButton: document.querySelector("#addTaskButton"),
      taskStatusFilter: document.querySelector("#taskStatusFilter"),
      statusSummary: document.querySelector("#statusSummary"),
      taskList: document.querySelector("#taskList"),
      timelineSearch: document.querySelector("#timelineSearch"),
      timelineTypeFilter: document.querySelector("#timelineTypeFilter"),
      timelinePersonFilter: document.querySelector("#timelinePersonFilter"),
      timelineStatusFilter: document.querySelector("#timelineStatusFilter"),
      timelineDateFilter: document.querySelector("#timelineDateFilter"),
      timelineListViewButton: document.querySelector("#timelineListViewButton"),
      timelineCalendarViewButton: document.querySelector("#timelineCalendarViewButton"),
      timelineSummary: document.querySelector("#timelineSummary"),
      timelineList: document.querySelector("#timelineList"),
      syncMode: document.querySelector("#syncMode"),
      docLink: document.querySelector("#docLink"),
      docStatus: document.querySelector("#docStatus"),
      sheetLink: document.querySelector("#sheetLink"),
      sheetStatus: document.querySelector("#sheetStatus"),
      syncNowButton: document.querySelector("#syncNowButton"),
      taskDialog: document.querySelector("#taskDialog"),
      taskForm: document.querySelector("#taskForm"),
      taskDialogTitle: document.querySelector("#taskDialogTitle"),
      taskTitleInput: document.querySelector("#taskTitleInput"),
      taskAssigneeInput: document.querySelector("#taskAssigneeInput"),
      taskStatusInput: document.querySelector("#taskStatusInput"),
      taskScheduledDateInput: document.querySelector("#taskScheduledDateInput"),
      taskDeadlineInput: document.querySelector("#taskDeadlineInput"),
      closeTaskDialogButton: document.querySelector("#closeTaskDialogButton"),
      cancelTaskButton: document.querySelector("#cancelTaskButton"),
      settingsDialog: document.querySelector("#settingsDialog"),
      settingsMode: document.querySelector("#settingsMode"),
      settingsLastSync: document.querySelector("#settingsLastSync"),
      exportButton: document.querySelector("#exportButton"),
      resetButton: document.querySelector("#resetButton"),
      peopleOptions: document.querySelector("#peopleOptions"),
      toast: document.querySelector("#toast"),
    });
  }

  function bindEvents() {
    els.dailyLogForm.addEventListener("submit", submitDailyLog);
    els.clearLogButton.addEventListener("click", clearDailyForm);
    els.addTaskButton.addEventListener("click", addTask);
    els.newTaskTitle.addEventListener("keydown", (event) => {
      if (event.key === "Enter") {
        event.preventDefault();
        addTask();
      }
    });

    els.taskStatusFilter.addEventListener("input", () => {
      state.taskFilter = els.taskStatusFilter.value;
      renderTasks();
    });

    [
      els.timelineSearch,
      els.timelineTypeFilter,
      els.timelinePersonFilter,
      els.timelineStatusFilter,
      els.timelineDateFilter,
    ].forEach((control) => control.addEventListener("input", updateTimelineFilters));

    els.timelineListViewButton.addEventListener("click", () => setTimelineView("list"));
    els.timelineCalendarViewButton.addEventListener("click", () => setTimelineView("calendar"));

    els.syncNowButton.addEventListener("click", () => loadState("Synced"));
    els.settingsButton.addEventListener("click", () => {
      renderSettings();
      els.settingsDialog.showModal();
    });
    els.exportButton.addEventListener("click", exportJson);
    els.resetButton.addEventListener("click", resetLocalData);
    els.taskForm.addEventListener("submit", saveTaskFromDialog);
    els.closeTaskDialogButton.addEventListener("click", closeTaskDialog);
    els.cancelTaskButton.addEventListener("click", closeTaskDialog);
  }

  async function loadState(successMessage = "") {
    await runAction(successMessage ? "Syncing..." : "", async () => {
      state.data = Data.normalizeData(await state.provider.loadState());
      els.logDate.value = Utils.todayInput();
      render();
      if (successMessage) showToast(successMessage);
    });
  }

  function render() {
    if (!state.data) return;
    renderProject();
    renderPeopleOptions();
    renderTasks();
    renderTimeline();
    renderSync();
    renderSettings();
  }

  function renderProject() {
    const { project } = state.data;
    const people = Data.getPeople(state.data).slice(0, 4);
    els.projectTitle.textContent = project.title;
    els.peopleSummary.textContent = people.join(" / ");
  }

  function renderPeopleOptions() {
    const people = Data.getPeople(state.data);
    els.peopleOptions.replaceChildren(
      ...people.map((person) => {
        const option = document.createElement("option");
        option.value = person;
        return option;
      })
    );

    const selectedPerson = els.timelinePersonFilter.value || "all";
    els.timelinePersonFilter.replaceChildren(
      option("all", "All"),
      ...people.map((person) => option(person, person))
    );
    els.timelinePersonFilter.value = people.includes(selectedPerson) ? selectedPerson : "all";

    if (!els.newTaskAssignee.value) els.newTaskAssignee.value = state.data.project.mentee;
  }

  function option(value, label) {
    const item = document.createElement("option");
    item.value = value;
    item.textContent = label;
    return item;
  }

  function renderTasks() {
    const tasks = state.data.tasks
      .filter((task) => matchesTaskFilter(task, state.taskFilter))
      .sort(sortTasks);

    const counts = countTasks();
    els.statusSummary.textContent = `${counts.not_started} not started / ${counts.in_progress} in progress / ${counts.waiting} waiting / ${counts.blocked} blocked / ${counts.done} done`;

    if (!tasks.length) {
      els.taskList.innerHTML = `<p class="empty-state">No tasks in this view.</p>`;
      return;
    }

    els.taskList.replaceChildren(...tasks.map(renderTaskRow));
  }

  function renderTaskRow(task) {
    const row = document.createElement("article");
    row.className = "task-row";

    const checkbox = document.createElement("input");
    checkbox.type = "checkbox";
    checkbox.checked = task.status === "done";
    checkbox.setAttribute("aria-label", `Mark ${task.title} done`);
    checkbox.addEventListener("change", () => {
      updateTask({ ...task, status: checkbox.checked ? "done" : "in_progress" });
    });

    const titleWrap = document.createElement("div");
    titleWrap.className = "task-title";
    const titleLine = document.createElement("div");
    titleLine.className = "task-heading";
    const titleButton = document.createElement("button");
    titleButton.className = "task-title-button";
    titleButton.type = "button";
    titleButton.textContent = task.title;
    titleButton.addEventListener("click", () => openTaskDialog(task.id));
    titleLine.append(renderTaskKey(task), titleButton);
    const meta = document.createElement("span");
    meta.className = "task-meta";
    meta.textContent = taskMeta(task);
    titleWrap.append(titleLine, meta, renderTaskDatePair(task));

    const status = document.createElement("select");
    status.className = `status-select ${task.status}`;
    status.setAttribute("aria-label", `Status for ${task.title}`);
    Object.entries(Config.statusLabels).forEach(([value, label]) => status.append(option(value, label)));
    status.value = task.status;
    status.addEventListener("change", () => updateTask({ ...task, status: status.value }));

    const edit = document.createElement("button");
    edit.className = "secondary-button compact-button";
    edit.type = "button";
    edit.textContent = "Edit";
    edit.addEventListener("click", () => openTaskDialog(task.id));

    const remove = document.createElement("button");
    remove.className = "delete-task";
    remove.type = "button";
    remove.textContent = "x";
    remove.setAttribute("aria-label", `Delete ${task.title}`);
    remove.addEventListener("click", () => deleteTask(task));

    row.append(checkbox, titleWrap, status, edit, remove);
    return row;
  }

  function renderTaskDatePair(task) {
    const wrap = document.createElement("span");
    wrap.className = "date-pair";

    if (!task.scheduledDate && !task.deadline) {
      const chip = document.createElement("span");
      chip.className = "date-chip empty";
      chip.textContent = "No dates";
      wrap.append(chip);
      return wrap;
    }

    if (task.scheduledDate) {
      const chip = document.createElement("span");
      chip.className = "date-chip do-date";
      chip.textContent = `Do ${Utils.formatShortDate(task.scheduledDate)}`;
      wrap.append(chip);
    }

    if (task.deadline) {
      const chip = document.createElement("span");
      chip.className = "date-chip deadline";
      chip.textContent = `Due ${Utils.formatShortDate(task.deadline)}`;
      wrap.append(chip);
    }

    return wrap;
  }

  function taskMeta(task) {
    const parts = [task.owner || "Unassigned", Config.statusLabels[task.status]];
    if (!task.scheduledDate && !task.deadline) parts.push("No dates");
    return parts.join(" / ");
  }

  function matchesTaskFilter(task, filter) {
    if (filter === "all") return true;
    if (filter === "active") return task.status !== "done";
    return task.status === filter;
  }

  function taskIdentity(task) {
    const index = Math.max(0, state.data.tasks.findIndex((item) => item.id === task.id));
    const number = index + 1;
    return {
      label: `T${number}`,
      tone: TASK_TONES[index % TASK_TONES.length],
    };
  }

  function renderTaskKey(task) {
    const identity = taskIdentity(task);
    const key = document.createElement("span");
    key.className = `task-key ${identity.tone}`;
    key.textContent = identity.label;
    key.title = `${identity.label}: ${task.title}`;
    return key;
  }

  function timelineTaskText(task, dateKind) {
    const pairedDate = dateKind === "do" && task.deadline
      ? `Due ${Utils.formatShortDate(task.deadline)}`
      : dateKind === "deadline" && task.scheduledDate
        ? `Do ${Utils.formatShortDate(task.scheduledDate)}`
        : "";
    return [
      task.owner || "Unassigned",
      Config.statusLabels[task.status],
      pairedDate,
    ].filter(Boolean).join(" / ");
  }

  function renderTimeline() {
    const items = getFilteredTimelineItems();
    renderTimelineViewToggle();
    els.timelineSummary.textContent = `${items.length} item${items.length === 1 ? "" : "s"} / ${state.timeline.view}`;
    els.timelineList.classList.toggle("calendar-view", state.timeline.view === "calendar");

    if (!items.length) {
      els.timelineList.innerHTML = `<p class="empty-state">No timeline items match these filters.</p>`;
      return;
    }

    if (state.timeline.view === "calendar") {
      renderTimelineCalendar(items);
      return;
    }

    const groups = groupByDate(items);
    els.timelineList.replaceChildren(...groups.map(renderTimelineGroup));
  }

  function renderTimelineViewToggle() {
    els.timelineListViewButton.classList.toggle("active", state.timeline.view === "list");
    els.timelineCalendarViewButton.classList.toggle("active", state.timeline.view === "calendar");
    els.timelineListViewButton.setAttribute("aria-pressed", String(state.timeline.view === "list"));
    els.timelineCalendarViewButton.setAttribute("aria-pressed", String(state.timeline.view === "calendar"));
  }

  function setTimelineView(view) {
    if (state.timeline.view === view) return;
    state.timeline.view = view;
    renderTimeline();
  }

  function getFilteredTimelineItems() {
    return buildTimelineItems()
      .filter((item) => state.timeline.type === "all" || item.type === state.timeline.type)
      .filter((item) => state.timeline.person === "all" || item.person === state.timeline.person)
      .filter((item) => state.timeline.status === "all" || item.status === state.timeline.status)
      .filter((item) => matchesDateFilter(item))
      .filter((item) => {
        const query = state.timeline.query;
        if (!query) return true;
        return [item.title, item.text, item.person, item.label, item.identityLabel].some((value) => Utils.includesText(value, query));
      })
      .sort((a, b) => sortDateKey(a.date).localeCompare(sortDateKey(b.date)) || a.title.localeCompare(b.title));
  }

  function buildTimelineItems() {
    const items = [];
    state.data.dailyLogs.forEach((log) => {
      const figureText = log.figureName || log.figureDescription
        ? `Figure: ${log.figureDescription || log.figureName}`
        : "";
      const sections = [log.workedOn, log.notes, log.blockers, log.nextStep, figureText].filter(Boolean).join(" ");
      items.push({
        id: log.id,
        type: "log",
        date: log.date,
        label: "Entry",
        title: "Daily entry",
        text: sections || "Entry saved.",
        person: "",
        status: "entry",
        hasFigure: Boolean(log.figureName || log.figureDescription),
      });
    });

    state.data.tasks.forEach((task) => {
      const identity = taskIdentity(task);
      const dates = [];
      if (task.scheduledDate) dates.push({ date: task.scheduledDate, kind: "do", label: "Do" });
      if (task.deadline) dates.push({ date: task.deadline, kind: "deadline", label: "Due" });
      if (!dates.length) dates.push({ date: "", kind: "unscheduled", label: "Unscheduled" });

      dates.forEach((date) => {
        items.push({
          id: `${task.id}-${date.kind}`,
          type: "task",
          date: date.date,
          dateKind: date.kind,
          label: date.label,
          title: task.title,
          text: timelineTaskText(task, date.kind),
          identityLabel: identity.label,
          identityTone: identity.tone,
          person: task.owner || "Unassigned",
          status: task.status,
          task,
        });
      });
    });

    return items;
  }

  function matchesDateFilter(item) {
    const filter = state.timeline.date;
    if (filter === "all") return true;
    if (filter === "unscheduled") return !item.date;
    if (!item.date) return false;

    const today = Utils.stripTime(new Date());
    const itemDate = Utils.parseDate(item.date);
    if (!itemDate) return false;
    if (filter === "today") return item.date === Utils.toDateInput(today);
    if (filter === "upcoming") return itemDate >= today;
    if (filter === "overdue") return item.type === "task" && item.status !== "done" && itemDate < today;
    return true;
  }

  function groupByDate(items) {
    const map = new Map();
    items.forEach((item) => {
      const key = item.date || "__unscheduled";
      if (!map.has(key)) map.set(key, []);
      map.get(key).push(item);
    });
    return Array.from(map.entries()).map(([date, groupItems]) => ({ date, items: groupItems }));
  }

  function renderTimelineGroup(group) {
    const section = document.createElement("section");
    section.className = "timeline-day";

    const heading = document.createElement("h3");
    heading.textContent = group.date === "__unscheduled" ? "Unscheduled" : Utils.formatLongDate(group.date);
    section.append(heading);

    const list = document.createElement("div");
    list.className = "timeline-items";
    list.replaceChildren(...group.items.map(renderTimelineItem));
    section.append(list);
    return section;
  }

  function renderTimelineCalendar(items) {
    const datedItems = items.filter((item) => item.date);
    const undatedItems = items.filter((item) => !item.date);
    const months = groupByMonth(datedItems);
    const sections = months.map(renderCalendarMonth);
    if (undatedItems.length) sections.push(renderCalendarUnscheduled(undatedItems));
    els.timelineList.replaceChildren(...sections);
  }

  function groupByMonth(items) {
    const map = new Map();
    items.forEach((item) => {
      const key = item.date.slice(0, 7);
      if (!map.has(key)) map.set(key, []);
      map.get(key).push(item);
    });
    return Array.from(map.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([month, monthItems]) => ({ month, items: monthItems }));
  }

  function renderCalendarMonth(group) {
    const [year, month] = group.month.split("-").map(Number);
    const firstDate = new Date(year, month - 1, 1);
    const daysInMonth = new Date(year, month, 0).getDate();
    const itemsByDate = groupByDate(group.items).reduce((map, day) => map.set(day.date, day.items), new Map());
    const section = document.createElement("section");
    section.className = "calendar-month";

    const heading = document.createElement("h3");
    heading.textContent = firstDate.toLocaleDateString([], { month: "long", year: "numeric" });
    section.append(heading);

    const grid = document.createElement("div");
    grid.className = "calendar-grid";
    ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].forEach((day) => {
      const header = document.createElement("div");
      header.className = "calendar-weekday";
      header.textContent = day;
      grid.append(header);
    });

    for (let index = 0; index < firstDate.getDay(); index += 1) {
      const empty = document.createElement("div");
      empty.className = "calendar-day empty";
      grid.append(empty);
    }

    for (let day = 1; day <= daysInMonth; day += 1) {
      const dateKey = `${group.month}-${String(day).padStart(2, "0")}`;
      grid.append(renderCalendarDay(day, dateKey, itemsByDate.get(dateKey) || []));
    }

    section.append(grid);
    return section;
  }

  function renderCalendarDay(day, dateKey, items) {
    const cell = document.createElement("div");
    cell.className = `calendar-day${dateKey === Utils.todayInput() ? " today" : ""}`;

    const number = document.createElement("div");
    number.className = "calendar-date-number";
    number.textContent = String(day);

    const events = document.createElement("div");
    events.className = "calendar-events";
    events.replaceChildren(...items.map(renderCalendarEvent));

    cell.append(number, events);
    return cell;
  }

  function renderCalendarEvent(item) {
    const event = document.createElement(item.type === "task" ? "button" : "div");
    event.className = `calendar-event ${item.type} ${item.dateKind || ""} ${item.identityTone || ""}`;
    if (item.type === "task") {
      event.type = "button";
      event.textContent = `${item.identityLabel} ${item.label}: ${item.title}`;
      event.title = `${item.identityLabel} ${item.label}: ${item.title} / ${item.text}`;
      event.addEventListener("click", () => openTaskDialog(item.task.id));
    } else {
      event.textContent = item.hasFigure ? "Entry + figure" : "Daily entry";
      event.title = item.text;
    }
    return event;
  }

  function renderCalendarUnscheduled(items) {
    const section = document.createElement("section");
    section.className = "calendar-unscheduled";
    const heading = document.createElement("h3");
    heading.textContent = "Unscheduled";
    const list = document.createElement("div");
    list.className = "timeline-items";
    list.replaceChildren(...items.map(renderTimelineItem));
    section.append(heading, list);
    return section;
  }

  function renderTimelineItem(item) {
    const article = document.createElement("article");
    article.className = `timeline-item ${item.type} ${item.dateKind || ""}`;

    const badge = document.createElement("span");
    badge.className = `timeline-badge ${item.type} ${item.status} ${item.dateKind || ""}`;
    badge.textContent = item.type === "task" ? item.label : item.label;

    const body = document.createElement("div");
    const title = document.createElement("strong");
    title.textContent = item.title;
    const text = document.createElement("p");
    text.textContent = item.text;
    if (item.type === "task") {
      const titleLine = document.createElement("div");
      titleLine.className = "task-heading timeline-title-line";
      titleLine.append(renderTaskKey(item.task), title);
      body.append(titleLine, text);
    } else {
      body.append(title, text);
    }
    article.append(badge, body);

    if (item.type === "task") {
      const edit = document.createElement("button");
      edit.className = "secondary-button compact-button";
      edit.type = "button";
      edit.textContent = "Edit";
      edit.addEventListener("click", () => openTaskDialog(item.task.id));
      article.append(edit);
    }

    return article;
  }

  function renderSync() {
    const sync = state.data.sync || {};
    els.syncMode.textContent = state.provider.mode === "google" ? "Google Drive connected" : "Local preview";
    setSyncLink(els.docLink, els.docStatus, sync.docUrl, sync.docName || "Not connected");
    setSyncLink(els.sheetLink, els.sheetStatus, sync.sheetUrl, sync.sheetName || "Not connected");
  }

  function setSyncLink(link, status, url, label) {
    status.textContent = label;
    if (url) {
      link.href = url;
      link.removeAttribute("aria-disabled");
    } else {
      link.href = "#";
      link.setAttribute("aria-disabled", "true");
    }
  }

  function renderSettings() {
    if (!state.data) return;
    els.settingsMode.textContent = state.provider.mode === "google" ? "Google Apps Script" : "Local preview";
    els.settingsLastSync.textContent = Utils.formatDateTime(state.data.sync?.lastSync);
  }

  async function submitDailyLog(event) {
    event.preventDefault();
    const formData = Object.fromEntries(new FormData(els.dailyLogForm).entries());
    const figureFile = els.figureInput.files[0];
    const figureDescription = String(formData.figureDescription || "").trim();
    const hasContent = ["workedOn", "notes", "blockers", "nextStep"].some((key) => formData[key]?.trim())
      || Boolean(figureFile);
    if (figureDescription && !figureFile) {
      showToast("Attach a figure before adding a figure description");
      return;
    }
    if (!hasContent) {
      showToast("Add at least one note before submitting");
      return;
    }

    let figurePayload;
    try {
      figurePayload = await buildFigurePayload(figureFile, figureDescription);
    } catch (error) {
      showToast(error.message);
      return;
    }

    const log = {
      id: Utils.createId("log"),
      date: formData.date,
      workedOn: formData.workedOn.trim(),
      notes: formData.notes.trim(),
      blockers: formData.blockers.trim(),
      nextStep: formData.nextStep.trim(),
      createdAt: new Date().toISOString(),
      ...figurePayload,
    };

    await runAction("Submitting...", async () => {
      state.data = Data.normalizeData(await state.provider.submitDailyLog(log));
      clearDailyForm();
      render();
      showToast(state.provider.mode === "google" ? "Submitted to Google Doc" : "Saved locally");
    });
  }

  function buildFigurePayload(file, description) {
    if (!file) {
      return Promise.resolve({
        figureName: "",
        figureMimeType: "",
        figureDescription: "",
        figureDataUrl: "",
      });
    }
    if (!file.type || !file.type.startsWith("image/")) {
      return Promise.reject(new Error("Choose an image file for the figure"));
    }
    if (file.size > MAX_FIGURE_BYTES) {
      return Promise.reject(new Error("Choose a figure under 5 MB"));
    }
    return readFileAsDataUrl(file).then((figureDataUrl) => ({
      figureName: file.name,
      figureMimeType: file.type,
      figureDescription: description,
      figureDataUrl,
    }));
  }

  function readFileAsDataUrl(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.addEventListener("load", () => resolve(String(reader.result || "")));
      reader.addEventListener("error", () => reject(new Error("Could not read the selected figure")));
      reader.readAsDataURL(file);
    });
  }

  async function addTask() {
    const title = els.newTaskTitle.value.trim();
    if (!title) {
      showToast("Add a task title");
      return;
    }

    const task = {
      id: Utils.createId("task"),
      title,
      status: els.newTaskStatus.value,
      owner: els.newTaskAssignee.value.trim() || state.data.project.mentee,
      scheduledDate: els.newTaskScheduledDate.value,
      deadline: els.newTaskDeadline.value,
      updatedAt: new Date().toISOString(),
    };

    await updateTask(task, "Task added");
    els.newTaskTitle.value = "";
    els.newTaskStatus.value = "not_started";
    els.newTaskScheduledDate.value = "";
    els.newTaskDeadline.value = "";
  }

  async function updateTask(task, message = "Task updated") {
    await runAction("Saving task...", async () => {
      state.data = Data.normalizeData(await state.provider.upsertTask({ ...task, updatedAt: new Date().toISOString() }));
      render();
      showToast(message);
    });
  }

  async function deleteTask(task) {
    if (!window.confirm(`Delete "${task.title}" from the task list?`)) return;
    await runAction("Deleting task...", async () => {
      state.data = Data.normalizeData(await state.provider.deleteTask(task.id));
      render();
      showToast("Task deleted");
    });
  }

  function openTaskDialog(taskId) {
    const task = state.data.tasks.find((item) => item.id === taskId);
    if (!task) return;
    state.editingTaskId = taskId;
    els.taskDialogTitle.textContent = task.title;
    els.taskTitleInput.value = task.title;
    els.taskAssigneeInput.value = task.owner || "";
    els.taskStatusInput.value = task.status;
    els.taskScheduledDateInput.value = task.scheduledDate || "";
    els.taskDeadlineInput.value = task.deadline || "";
    els.taskDialog.showModal();
  }

  function closeTaskDialog() {
    state.editingTaskId = "";
    els.taskDialog.close();
  }

  async function saveTaskFromDialog(event) {
    event.preventDefault();
    const existing = state.data.tasks.find((task) => task.id === state.editingTaskId);
    if (!existing) return;
    const updated = {
      ...existing,
      title: els.taskTitleInput.value.trim(),
      owner: els.taskAssigneeInput.value.trim() || "Unassigned",
      status: els.taskStatusInput.value,
      scheduledDate: els.taskScheduledDateInput.value,
      deadline: els.taskDeadlineInput.value,
    };
    if (!updated.title) {
      showToast("Task title is required");
      return;
    }
    await updateTask(updated);
    closeTaskDialog();
  }

  function updateTimelineFilters() {
    state.timeline = {
      query: els.timelineSearch.value.trim(),
      type: els.timelineTypeFilter.value,
      person: els.timelinePersonFilter.value,
      status: els.timelineStatusFilter.value,
      date: els.timelineDateFilter.value,
      view: state.timeline.view,
    };
    renderTimeline();
  }

  function clearDailyForm() {
    els.dailyLogForm.reset();
    els.logDate.value = Utils.todayInput();
  }

  function exportJson() {
    const blob = new Blob([JSON.stringify(state.data, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "mentoring-workspace.json";
    document.body.append(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  }

  function resetLocalData() {
    if (state.provider.mode !== "local") {
      showToast("Reset is only available in local preview");
      return;
    }
    if (!window.confirm("Reset local data to the starter plan?")) return;
    localStorage.removeItem(Config.storageKey);
    loadState("Local data reset");
  }

  async function runAction(label, action) {
    if (state.busy) return;
    state.busy = true;
    setBusy(true, label);
    try {
      await action();
    } catch (error) {
      showToast(error.message || "Something went wrong");
    } finally {
      state.busy = false;
      setBusy(false);
    }
  }

  function setBusy(isBusy, label = "") {
    [
      els.submitLogButton,
      els.addTaskButton,
      els.syncNowButton,
    ].forEach((button) => {
      if (button) button.disabled = isBusy;
    });
    if (isBusy && label) showToast(label);
  }

  function countTasks() {
    return state.data.tasks
      .reduce(
        (counts, taskItem) => {
          counts[taskItem.status] += 1;
          return counts;
        },
        { not_started: 0, in_progress: 0, waiting: 0, blocked: 0, done: 0 }
      );
  }

  function sortTasks(a, b) {
    return statusRank(a.status) - statusRank(b.status)
      || dateRank(a.scheduledDate || a.deadline).localeCompare(dateRank(b.scheduledDate || b.deadline))
      || a.title.localeCompare(b.title);
  }

  function statusRank(status) {
    return { blocked: 0, waiting: 1, in_progress: 2, not_started: 3, done: 4 }[status] ?? 5;
  }

  function dateRank(value) {
    return value || "9999-99-99";
  }

  function sortDateKey(value) {
    return value || "9999-99-99";
  }

  function showToast(message) {
    els.toast.textContent = message;
    els.toast.classList.add("visible");
    clearTimeout(showToast.timer);
    showToast.timer = setTimeout(() => els.toast.classList.remove("visible"), 2400);
  }

  App.UI = {
    init,
  };
})(window, document);


document.addEventListener("DOMContentLoaded", () => {
  window.MentoringWorkspace.UI.init();
});

